/*
 * This source file was generated by the Gradle 'init' task
 */
package org.parser;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appTestOrders() {
        OrderTracker classUnderTest = new OrderTracker();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
